/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FunTyper: typeof import('./src/components/FunTyper.vue')['default']
    ModelViewer: typeof import('./src/components/ModelViewer.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PromptInput: typeof import('./src/components/PromptInput.vue')['default']
    ResultViewer: typeof import('./src/components/ResultViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
